### ISSUE TITLE
[question] About the operations implementation.

### ISSUE THREAD

**Issue by enricopolanski** [YBogomolov/workshop-edsl-in-typescript#1]
I am following the workshop with great interest.

I wanted to ask the reason behind using the `class` encoding behind the operations.

Is it possible to encode the same operations with a constructor function?

I apologize if this was already answered in the workshop, I might have missed it.

**Comment by YBogomolov** [comment]
The answer should be around here: https://youtu.be/hTnxaB52awA?t=1805

Basically, your operations need to be higher-kinded types. In `fp-ts` they are emulated using [this approach](https://www.cl.cam.ac.uk/~jdy22/papers/lightweight-higher-kinded-polymorphism.pdf) (see also [this explanation](https://github.com/gcanti/fp-ts/blob/master/docs/guides/HKT.md)).

If you take a look at the implementation of [liftF](https://github.com/gcanti/fp-ts-contrib/blob/master/src/Free.ts#L64), you'll see that it requires its parameter to be a `HKT`. This interface is defined in `fp-ts` [like so](https://github.com/gcanti/fp-ts/blob/master/src/HKT.ts#L11-L14):

```ts
interface HKT<URI, A> {
  readonly _URI: URI
  readonly _A: A
}
```

If you happen to make constructor functions work, please let me know.
