### ISSUE TITLE
[Question] About the `getInstanceFor` function. 

### ISSUE THREAD

**Issue by SeungUkLee** [YBogomolov/workshop-edsl-in-typescript#3]
Thank you for great workshop!

I'm studying the workshop with great interest.

As the title asks, what is the `getInstanceFor` function in `src/workshop/tagless-final/api.ts` ?  

I am curious about how to utilize `getInstanceFor` function.

**Comment by YBogomolov** [comment]
Hi! Thank you for your kind words :)

I'm talking about `getInstanceFor` function here: https://youtu.be/hTnxaB52awA?list=PLh-Tpzes3IeqEgMo2dy-1mVyU9hQ_mY9z&t=8701

Basically, it's just a convenience method for working using a specific monad instance. I like to utilize it as a part of a public API of my projects — for example, here's this function in `kleisli-ts`: https://github.com/YBogomolov/kleisli-ts/blob/develop/src/kleisli.ts#L465

**Comment by SeungUkLee** [comment]
Thanks for your response! I will study the references.

**Comment by YBogomolov** [comment]
Okay, I will close this issue for now, feel free to reopen if needed.
